# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fleet.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("fleet.proto", :syntax => :proto3) do
    add_message "proto.fleet.FleetService" do
      oneof :fservice do
        optional :share_ride, :message, 1, "proto.fleet.FleetService.ShareRideSerivce"
        optional :deliver, :message, 2, "proto.fleet.FleetService.DeliverSerivce"
      end
    end
    add_message "proto.fleet.FleetService.ShareRideSerivce" do
      optional :capacity, :int32, 1
      optional :occupied_seats, :int32, 2
      optional :available_seats, :int32, 3
      optional :non_smoking, :bool, 4
      optional :price_per_km, :int32, 5
    end
    add_message "proto.fleet.FleetService.DeliverSerivce" do
      optional :item, :string, 1
      optional :unit, :string, 2
      optional :num, :int32, 3
      optional :avail, :int32, 4
      repeated :demand_ids, :int64, 5
    end
    add_message "proto.fleet.Fleet" do
      optional :vehicle_id, :int32, 1
      optional :status, :int32, 2
      optional :coord, :message, 3, "proto.fleet.Fleet.Coord"
      optional :angle, :float, 4
      optional :speed, :int32, 5
      repeated :services, :message, 6, "proto.fleet.FleetService"
      repeated :demands, :int32, 7
    end
    add_message "proto.fleet.Fleet.Coord" do
      optional :lat, :float, 1
      optional :lon, :float, 2
    end
  end
end

module Proto
  module Fleet
    FleetService = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.fleet.FleetService").msgclass
    FleetService::ShareRideSerivce = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.fleet.FleetService.ShareRideSerivce").msgclass
    FleetService::DeliverSerivce = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.fleet.FleetService.DeliverSerivce").msgclass
    Fleet = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.fleet.Fleet").msgclass
    Fleet::Coord = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.fleet.Fleet.Coord").msgclass
  end
end
