# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: nodeapi.proto for package 'nodeapi'

require 'grpc'
require 'nodeapi_pb'

module Nodeapi
  module Node
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'nodeapi.Node'

      rpc :RegisterNode, NodeInfo, NodeID
      rpc :QueryNode, NodeID, NodeInfo
      rpc :KeepAlive, NodeUpdate, Response
      rpc :UnRegisterNode, NodeID, Response
    end

    Stub = Service.rpc_stub_class
  end
end
