# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nodeapi.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("nodeapi.proto", :syntax => :proto3) do
    add_message "nodeapi.NodeInfo" do
      optional :node_name, :string, 1
      optional :node_type, :enum, 2, "nodeapi.NodeType"
      optional :server_info, :string, 3
      optional :node_pbase_version, :string, 4
      optional :with_node_id, :int32, 5
      optional :cluster_id, :int32, 6
      optional :area_id, :string, 7
      repeated :channelTypes, :uint32, 8
    end
    add_message "nodeapi.NodeID" do
      optional :node_id, :int32, 1
      optional :secret, :fixed64, 2
      optional :server_info, :string, 3
      optional :keepalive_duration, :int32, 4
    end
    add_message "nodeapi.NodeUpdate" do
      optional :node_id, :int32, 1
      optional :secret, :fixed64, 2
      optional :update_count, :int32, 3
      optional :node_status, :int32, 4
      optional :node_arg, :string, 5
    end
    add_message "nodeapi.Response" do
      optional :ok, :bool, 1
      optional :command, :enum, 2, "nodeapi.KeepAliveCommand"
      optional :err, :string, 3
    end
    add_enum "nodeapi.NodeType" do
      value :PROVIDER, 0
      value :SERVER, 1
      value :GATEWAY, 2
    end
    add_enum "nodeapi.KeepAliveCommand" do
      value :NONE, 0
      value :RECONNECT, 1
      value :SERVER_CHANGE, 2
    end
  end
end

module Nodeapi
  NodeInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("nodeapi.NodeInfo").msgclass
  NodeID = Google::Protobuf::DescriptorPool.generated_pool.lookup("nodeapi.NodeID").msgclass
  NodeUpdate = Google::Protobuf::DescriptorPool.generated_pool.lookup("nodeapi.NodeUpdate").msgclass
  Response = Google::Protobuf::DescriptorPool.generated_pool.lookup("nodeapi.Response").msgclass
  NodeType = Google::Protobuf::DescriptorPool.generated_pool.lookup("nodeapi.NodeType").enummodule
  KeepAliveCommand = Google::Protobuf::DescriptorPool.generated_pool.lookup("nodeapi.KeepAliveCommand").enummodule
end
